import GlobalStyles from "@/components/GlobalStyles";
import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import StyledComponentsRegistry from "@/components/StyledComponentsRegistry";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <GlobalStyles />
        <body className={raleway.className}>{children}</body>
      </StyledComponentsRegistry>
    </html>
  );
}
